name: Upload and download test on test-pypi
on:
  workflow_dispatch:
  pull_request:

jobs:
  upload_to_test_pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry poetry-dynamic-versioning twine

    - name: Build and publish
      env:
        TEST_PYPI_URL: https://test.pypi.org/legacy/
        REPO: test-pypi
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry config repositories.$REPO $TEST_PYPI_URL
        poetry publish -r $REPO --build --username $TWINE_USERNAME --password $TWINE_PASSWORD

  download_from_test_pypi:
    needs: upload_to_test_pypi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Install from test-pypi
      env:
        URL: https://test.pypi.org/simple/
        EXT_URL: https://pypi.org/simple/
        PACKAGE_NAME: derm_tiff
      run: |
        python -m pip install --index-url $URL --extra-index-url $EXT_URL $PACKAGE_NAME